### ISSUE TITLE
eslint-plugin-import error on '.svg?inline' in component

### ISSUE THREAD

**Issue by laSinteZ** [nuxt-community/svg-module#4]
## Description
For some reason, `eslint-plugin-import` triggers with
`
  10:18  error  Unable to resolve path to module '~/assets/example.svg?inline'  import/no-unresolved
`

but OK with `<img src="~/assets/example.svg?data">`
I understand that problem most probably is in the `eslint-plugin-import` but maybe we can solve it here :)

## How to repeat
https://github.com/laSinteZ/nuxt-svg-bug/tree/bug/eslint-plugin-import
```
yarn
yarn lint
```

**Comment by laSinteZ** [comment]
(for all seeking for a temporary "fix") I temporarily disabled this rule for SVGs with
```
rules: {
  'import/no-unresolved': [
    'error',
    {
      'ignore': [ '\.svg' ]
    }
  ]
}
```
in `.eslintrc.js`

**Comment by sam3d** [comment]
@laSinteZ Did you arrive at a permanent solution for this?

**Comment by brhx** [comment]
@laSinteZ Thank you for this and for providing both a reproduction link and a temporary fix! I'm afraid I won't be able to get round to implementing a fix for this within the module for a little while.

**Comment by risedack1** [comment]
I have slightly improved the solution to this issue by adding support for specific modifiers when importing SVG files. Instead of completely ignoring all .svg files in import/no-unresolved, my approach only ignores .svg files with certain parameters, such as ?react, ?inline, etc. This allows ESLint to continue properly checking regular SVG files without parameters.

`
"import/no-unresolved":[
  "error",
  {
    "ignore": ["\\.svg(\\?{inline})?$"]
  }
]
`

Here, {inline} represents any value after ?, such as ?react, ?data, ?icon, etc. This makes the exclusion more flexible and targeted.
