### ISSUE TITLE
How to import SVG Icons from node_modules folder?

### ISSUE THREAD

**Issue by slidenerd** [nuxt-community/svg-module#54]
- If the icons were present in assets directory, the documentation is straightforward
- In my case I am trying to use [THIS](https://github.com/spothq/cryptocurrency-icons) library
- It gets installed and the svg icons it contains are present in node_modules folder
- Can this module import icons from node_modules directory
- How to use it in say pages/index.vue
- Thank you for your response in advance

**Comment by azrikahar** [comment]
I had the same question when I first started using this module, so let me first share an example based on the documentation, then I'll share 2 possible setups I have used to simplify things since I feel like writing `import`s and adding them to the `components` option of the Vue component can get tedious very fast.

## CodeSandbox showcasing Option 1 & Option 3 usage

Link: https://codesandbox.io/s/smoosh-snowflake-tsnqc

`<CryptoIconMana />` is the one using Option 1, the rest are using Option 3.

# Options

## Option 1: Adapted from the documentations' `vue-svg-loader` example

```vue
<template>
  <CryptoIconMana />
</template>

<script>
  import CryptoIconMana from 'cryptocurrency-icons/svg/color/mana.svg?inline'

  export default {
    components: { CryptoIconMana },
  };
</script>
```

This option is very similar to the one you mentioned, so hopefully it's straightforward as well.

## Option 2: Create a functional component with no treeshaking

### /components/CryptoIcon.vue

```vue
<template functional>
  <component :is="$options.cryptoIconComponent(props.name)" />
</template>

<script>
export default {
  props: {
    name: {
      type: String,
      default: () => null,
    },
  },
  cryptoIconComponent(name) {
    return name
      ? require(`cryptocurrency-icons/svg/color/${name}.svg?inline`)
      : require(`cryptocurrency-icons/svg/color/generic.svg?inline`)
  },
}
</script>
```

### /pages/index.vue

```vue
<template>
  <div>
    <CryptoIcon name="btc" />
    <CryptoIcon />
  </div>
</template>
```

- **Pros**
  - No need for multiple `require()` statements like in Option 3 below
  - Have a fallback to the generic icon [as mentioned in the cryptocurrency-icons README.md](https://github.com/spothq/cryptocurrency-icons#cryptocurrency-icons) if you only used `<CryptoIcon />` without using the `name` props.
- **Cons**
  - Since we used this concatenated `require` statement: `require(`cryptocurrency-icons/svg/color/${name}.svg?inline`)`, webpack will **IMPORT ALL SVGs from the `cryptocurrency-icons/svg/color` folder** since it doesn't know what you might use for the `name` prop. This will make your final production bundle be quite big, especially if you are using library with a ton of icons. However if you are certain your site or web app will definitely use almost all or every icons in the library, then you can proceed with this solution.

## Option 3: Create a functional component with treeshaking

### /components/CryptoIcon.vue

```vue
<template functional>
  <component :is="$options.cryptoIconComponent(props.name)" />
</template>

<script>
const cryptoIcons = {
  btc: require('cryptocurrency-icons/svg/color/btc.svg?inline'),
  eth: require('cryptocurrency-icons/svg/color/eth.svg?inline'),
  usdt: require('cryptocurrency-icons/svg/color/usdt.svg?inline'),
  // add as many as you want over here
}

export default {
  props: {
    name: {
      type: String,
      required: true,
      validator(value) {
        return Object.prototype.hasOwnProperty.call(cryptoIcons, value)
      },
    },
  },
  cryptoIconComponent(name) {
    return cryptoIcons[name]
  },
}
</script>
```

### /pages/index.vue

```vue
<template>
  <div>
    <CryptoIcon name="btc" />
    <CryptoIcon name="eth" />
    <CryptoIcon name="usdt" />
  </div>
</template>
```

- **Pros**
  - Have a validation on the names you used by matching it vs the names (object keys) in the `cryptoIcons` object. If you didnt provide it or you provided a name that does not exist, it will throw a warning like so:
  ![chrome_eFYesdUVSE](https://user-images.githubusercontent.com/42867097/91530325-7dbc7100-e93d-11ea-8103-c57cdf790064.png)
  - Have correct treeshaking so your final bundle will be much smaller compared to Option 2 approach since you are only including the icons you need. **This option is recommended if you just want to use a few of the icons and want to keep the bundle smaller.**

- **Cons**
  - needs multiple `require()` statements

---

Hope these helps :) Feel free to ask me any further questions.

**Comment by slidenerd** [comment]
thank you sooo much!
