### ISSUE TITLE
nuxt-svg: Unexpected '.svg' rule in the webpack configuration

### ISSUE THREAD

**Issue by ThibautGrx** [nuxt-community/svg-module#68]
**Versions**

nuxt: v2.14.7
node: v12.16.1

**Reproduction**

**Additional Details**

{ mode: 'universal', target: 'static', modules: [ '@nuxtjs/svg' ] }

 **Steps to reproduce**
Run command nuxt dev or nuxt generate

 **What is Expected?**
Success

**What is actually happening?**

`ERROR nuxt-svg: Unexpected '.svg' rule in the webpack configuration`

**Comment by sougiovn** [comment]
I was having the same issue as you, even with the fix #57 

I "resolved" it by removing another module I was using for optimizing images: @aceforth/nuxt-optimized-images.

It was impacting the execution of `@nuxtjs/svg` because it was "imported" before `@nuxtjs/svg`, removing it everything worked well.

Importing it again, but after importing `@nuxtjs/svg` raises another error, but in the `vue-svg-loader` instead of `@nuxtjs/svg`.

**Comment by xmalbors** [comment]
I placed the module _@nuxtjs/svg_ after the module _@aceforth/nuxt-optimized-images_

`buildModules: [
  '@aceforth/nuxt-optimized-images',
  "@nuxtjs/svg",
]`

 and configured the module not to optimize svg files.

`optimizedImages: {
  optimizeImages: true,
  handleImages: ['jpeg', 'png', 'webp', 'gif']
}`

**Comment by nicolas-cusan** [comment]
Hello I am having this issue, even when using `@nuxtjs/svg` as the only build module.

- `@nuxtjs/svg` version `"^0.3.0"`
- `nuxt version `"^2.15.7"`

I suspect that `@nuxtjs/svg` gets executed before the custom `svg` rule is executed.

Anybody got a fix?

**Comment by manuelodelain** [comment]
Hi @nicolas-cusan I can't reproduce the issue. Can you provide a minimal example please?

**Comment by ThibautGrx** [comment]
@xmalbors solution solves the issue for me. 

> and configured the module not to optimize svg files.
> 
> `optimizedImages: { optimizeImages: true, handleImages: ['jpeg', 'png', 'webp', 'gif'] }`

I was using : 
```
   "@aceforth/nuxt-optimized-images": "^1.3.0",
    "@nuxtjs/svg": "^0.3.0"
```
