### ISSUE TITLE
Error in Microsoft Edge and IE 11

### ISSUE THREAD

**Issue by ladislavsulc** [nuxt-community/svg-module#9]
Hi,

I am using the latest Nuxt with your nice module. I have noticed that since then I have an error within our "beloved" browsers like Edge and IE11.

Screen: https://i.imgur.com/RI2eJYn.png

Error message: `SCRIPT1028: SCRIPT1028: Expected identifier, string or number`

You can verify the errors also here in staging: [https://timework.netlify.com](https://timework.netlify.com)

If by any means I am mistaken and it has nothing to do with your module, I apologize.

Thank you.

**Comment by brhx** [comment]
Thank you for your issue! I'll be able to take a look at this in the next couple of days.

**Comment by ladislavsulc** [comment]
Thank you for your time!

**Comment by ladislavsulc** [comment]
Might be useful later: https://github.com/visualfanatic/vue-svg-loader/issues/63

**Comment by simllll** [comment]
Just ran into the same issue, any ideas to workaround this in the meantime?

Regards

**Comment by ladislavsulc** [comment]
@simllll I'll get to coding during the weekend. I have to find a solution within a week so I will keep you posted.

**Comment by brhx** [comment]
I'm sorry I've been so busy guys. I'll happily review and accept any PR's @ladislavsulc, thank you for very much for your help!

**Comment by simllll** [comment]
So far as I can say the origin of this issue lies in https://github.com/visualfanatic/svg-to-vue 
https://github.com/visualfanatic/svg-to-vue/blob/1232c45a302f5a654be0d6444aeca15492e03d4f/index.js#L82
as they have changed the export, iexplorer cannot handle it. and it does not get babbled.

If you look in the master branch of the svg-to-vue though, it seems they have completly rewritten this part already (https://github.com/visualfanatic/svg-to-vue/blob/master/index.js). Maybe it works with the current code already, but it's just not published yet?

regards

**Comment by ladislavsulc** [comment]
Sorry guys, I am more a designer than a JS dev so I will have to leave this to the more skilled people. In the meantime, I will have to go with https://github.com/Developmint/nuxt-svg-loader since I need to support IE11 and Edge as well.

**Comment by suits-at** [comment]
@simllll and I got it running with a little workaround: We have added `babel-loader` on client, which seems to do the job. I also created a PR with this fix included (#10). Hopefully this also works for others.

**Comment by brhx** [comment]
Closed with #10 and released in `v0.1.6`.
